//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vsempoka
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ед измер.
    /// </summary>
    // *** Start programmer edit section *** (ЕдИзмер CustomAttributes)

    // *** End programmer edit section *** (ЕдИзмер CustomAttributes)
    public enum ЕдИзмер
    {
        
        // *** Start programmer edit section *** (ЕдИзмер.Шт CustomAttributes)

        // *** End programmer edit section *** (ЕдИзмер.Шт CustomAttributes)
        [Caption("Шт")]
        Шт,
        
        // *** Start programmer edit section *** (ЕдИзмер.Тонн CustomAttributes)

        // *** End programmer edit section *** (ЕдИзмер.Тонн CustomAttributes)
        [Caption("Тонн")]
        Тонн,
        
        // *** Start programmer edit section *** (ЕдИзмер.Кг CustomAttributes)

        // *** End programmer edit section *** (ЕдИзмер.Кг CustomAttributes)
        [Caption("Кг")]
        Кг,
        
        // *** Start programmer edit section *** (ЕдИзмер.Л CustomAttributes)

        // *** End programmer edit section *** (ЕдИзмер.Л CustomAttributes)
        [Caption("Л")]
        Л,
    }
}
