//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vsempoka
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состоян заказа.
    /// </summary>
    // *** Start programmer edit section *** (СостоянЗаказа CustomAttributes)

    // *** End programmer edit section *** (СостоянЗаказа CustomAttributes)
    public enum СостоянЗаказа
    {
        
        // *** Start programmer edit section *** (СостоянЗаказа.НеДоставлен CustomAttributes)

        // *** End programmer edit section *** (СостоянЗаказа.НеДоставлен CustomAttributes)
        [Caption("Не доставлен")]
        НеДоставлен,
        
        // *** Start programmer edit section *** (СостоянЗаказа.Доставлен CustomAttributes)

        // *** End programmer edit section *** (СостоянЗаказа.Доставлен CustomAttributes)
        [Caption("Доставлен")]
        Доставлен,
        
        // *** Start programmer edit section *** (СостоянЗаказа.ВОбработке CustomAttributes)

        // *** End programmer edit section *** (СостоянЗаказа.ВОбработке CustomAttributes)
        [Caption("В обработке")]
        ВОбработке,
        
        // *** Start programmer edit section *** (СостоянЗаказа.Отменен CustomAttributes)

        // *** End programmer edit section *** (СостоянЗаказа.Отменен CustomAttributes)
        [Caption("Отменен")]
        Отменен,
    }
}
