//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vsempoka
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Формир док распр.
    /// </summary>
    // *** Start programmer edit section *** (ФормирДокРаспр CustomAttributes)

    // *** End programmer edit section *** (ФормирДокРаспр CustomAttributes)
    [AutoAltered()]
    [Caption("Формирование документа распределения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормирДокРаспрE", new string[] {
            "Дата as \'Дата\'",
            "НомерДокРаспред as \'Номер документа распределения\'",
            "ДокумПостав as \'Номер документа поставки\'",
            "ДокумПостав.Клиенты.Заказчик as \'Заказчик\'",
            "ДокумПостав.Клиенты.АдресПоствки as \'Адрес поставки\'",
            "ДокумПостав.Клиенты.Телефон as \'Телефон\'",
            "СписокБарж as \'Номер баржи\'",
            "ПунктПогрузки as \'Адрес погрузки\'",
            "СписокКонтей as \'Номер контейнера\'"})]
    [MasterViewDefineAttribute("ФормирДокРаспрE", "ДокумПостав", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерДокПост")]
    [MasterViewDefineAttribute("ФормирДокРаспрE", "СписокБарж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерБаржи")]
    [MasterViewDefineAttribute("ФормирДокРаспрE", "ПунктПогрузки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [MasterViewDefineAttribute("ФормирДокРаспрE", "СписокКонтей", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКонтей")]
    [View("ФормирДокРаспрL", new string[] {
            "Дата as \'Дата\'",
            "НомерДокРаспред as \'Номер документа распределения\'",
            "ДокумПостав.Дата as \'Номер документа поставки\'",
            "СписокБарж.НомерБаржи as \'Номер баржи\'",
            "ПунктПогрузки.Адрес as \'Адрес погрузки\'",
            "СписокКонтей.НомерКонтей as \'Номер контейнера\'"})]
    public class ФормирДокРаспр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомерДокРаспред;
        
        private IIS.Vsempoka.ДокумПостав fДокумПостав;
        
        private IIS.Vsempoka.СписокКонтей fСписокКонтей;
        
        private IIS.Vsempoka.СписокБарж fСписокБарж;
        
        private IIS.Vsempoka.ПунктПогрузки fПунктПогрузки;
        
        // *** Start programmer edit section *** (ФормирДокРаспр CustomMembers)

        // *** End programmer edit section *** (ФормирДокРаспр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДокРаспр.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормирДокРаспр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.Дата Get start)

                // *** End programmer edit section *** (ФормирДокРаспр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормирДокРаспр.Дата Get end)

                // *** End programmer edit section *** (ФормирДокРаспр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.Дата Set start)

                // *** End programmer edit section *** (ФормирДокРаспр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормирДокРаспр.Дата Set end)

                // *** End programmer edit section *** (ФормирДокРаспр.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДокРаспред.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДокРаспр.НомерДокРаспред CustomAttributes)

        // *** End programmer edit section *** (ФормирДокРаспр.НомерДокРаспред CustomAttributes)
        public virtual int НомерДокРаспред
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.НомерДокРаспред Get start)

                // *** End programmer edit section *** (ФормирДокРаспр.НомерДокРаспред Get start)
                int result = this.fНомерДокРаспред;
                // *** Start programmer edit section *** (ФормирДокРаспр.НомерДокРаспред Get end)

                // *** End programmer edit section *** (ФормирДокРаспр.НомерДокРаспред Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.НомерДокРаспред Set start)

                // *** End programmer edit section *** (ФормирДокРаспр.НомерДокРаспред Set start)
                this.fНомерДокРаспред = value;
                // *** Start programmer edit section *** (ФормирДокРаспр.НомерДокРаспред Set end)

                // *** End programmer edit section *** (ФормирДокРаспр.НомерДокРаспред Set end)
            }
        }
        
        /// <summary>
        /// Формир док распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДокРаспр.ДокумПостав CustomAttributes)

        // *** End programmer edit section *** (ФормирДокРаспр.ДокумПостав CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокумПостав"})]
        [NotNull()]
        public virtual IIS.Vsempoka.ДокумПостав ДокумПостав
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.ДокумПостав Get start)

                // *** End programmer edit section *** (ФормирДокРаспр.ДокумПостав Get start)
                IIS.Vsempoka.ДокумПостав result = this.fДокумПостав;
                // *** Start programmer edit section *** (ФормирДокРаспр.ДокумПостав Get end)

                // *** End programmer edit section *** (ФормирДокРаспр.ДокумПостав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.ДокумПостав Set start)

                // *** End programmer edit section *** (ФормирДокРаспр.ДокумПостав Set start)
                this.fДокумПостав = value;
                // *** Start programmer edit section *** (ФормирДокРаспр.ДокумПостав Set end)

                // *** End programmer edit section *** (ФормирДокРаспр.ДокумПостав Set end)
            }
        }
        
        /// <summary>
        /// Формир док распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДокРаспр.ПунктПогрузки CustomAttributes)

        // *** End programmer edit section *** (ФормирДокРаспр.ПунктПогрузки CustomAttributes)
        [PropertyStorage(new string[] {
                "ПунктПогрузки"})]
        [NotNull()]
        public virtual IIS.Vsempoka.ПунктПогрузки ПунктПогрузки
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.ПунктПогрузки Get start)

                // *** End programmer edit section *** (ФормирДокРаспр.ПунктПогрузки Get start)
                IIS.Vsempoka.ПунктПогрузки result = this.fПунктПогрузки;
                // *** Start programmer edit section *** (ФормирДокРаспр.ПунктПогрузки Get end)

                // *** End programmer edit section *** (ФормирДокРаспр.ПунктПогрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.ПунктПогрузки Set start)

                // *** End programmer edit section *** (ФормирДокРаспр.ПунктПогрузки Set start)
                this.fПунктПогрузки = value;
                // *** Start programmer edit section *** (ФормирДокРаспр.ПунктПогрузки Set end)

                // *** End programmer edit section *** (ФормирДокРаспр.ПунктПогрузки Set end)
            }
        }
        
        /// <summary>
        /// Формир док распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДокРаспр.СписокБарж CustomAttributes)

        // *** End programmer edit section *** (ФормирДокРаспр.СписокБарж CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокБарж"})]
        [NotNull()]
        public virtual IIS.Vsempoka.СписокБарж СписокБарж
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.СписокБарж Get start)

                // *** End programmer edit section *** (ФормирДокРаспр.СписокБарж Get start)
                IIS.Vsempoka.СписокБарж result = this.fСписокБарж;
                // *** Start programmer edit section *** (ФормирДокРаспр.СписокБарж Get end)

                // *** End programmer edit section *** (ФормирДокРаспр.СписокБарж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.СписокБарж Set start)

                // *** End programmer edit section *** (ФормирДокРаспр.СписокБарж Set start)
                this.fСписокБарж = value;
                // *** Start programmer edit section *** (ФормирДокРаспр.СписокБарж Set end)

                // *** End programmer edit section *** (ФормирДокРаспр.СписокБарж Set end)
            }
        }
        
        /// <summary>
        /// Формир док распр.
        /// </summary>
        // *** Start programmer edit section *** (ФормирДокРаспр.СписокКонтей CustomAttributes)

        // *** End programmer edit section *** (ФормирДокРаспр.СписокКонтей CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокКонтей"})]
        [NotNull()]
        public virtual IIS.Vsempoka.СписокКонтей СписокКонтей
        {
            get
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.СписокКонтей Get start)

                // *** End programmer edit section *** (ФормирДокРаспр.СписокКонтей Get start)
                IIS.Vsempoka.СписокКонтей result = this.fСписокКонтей;
                // *** Start programmer edit section *** (ФормирДокРаспр.СписокКонтей Get end)

                // *** End programmer edit section *** (ФормирДокРаспр.СписокКонтей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормирДокРаспр.СписокКонтей Set start)

                // *** End programmer edit section *** (ФормирДокРаспр.СписокКонтей Set start)
                this.fСписокКонтей = value;
                // *** Start programmer edit section *** (ФормирДокРаспр.СписокКонтей Set end)

                // *** End programmer edit section *** (ФормирДокРаспр.СписокКонтей Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормирДокРаспрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирДокРаспрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирДокРаспрE", typeof(IIS.Vsempoka.ФормирДокРаспр));
                }
            }
            
            /// <summary>
            /// "ФормирДокРаспрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормирДокРаспрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормирДокРаспрL", typeof(IIS.Vsempoka.ФормирДокРаспр));
                }
            }
        }
    }
}
